site_name: TiPi framework
docs_dir: docs
site_dir: site
pages:
- 'Home': index.md
- 'User Guide':
   - 'Framework': framework.md
   - 'Shaped Arrays': shaped-arrays.md
   - 'Making Arrays': array-factory.md
   - 'Vectors': vectors.md
- 'Developpers':
   - 'Code Maintenance': devel.md
   - 'New Vector Types': new-vector-types.md
   - 'The TiPi Preprocessor': tpp.md
- 'Tools': deconv-tool.md
- 'About':
   - 'License': license.md
   - 'News': news.md
